insert into album2 ( AlbumId, Title, ArtistId) values (1, 'For Those About To Rock We Salute You', 1);
insert into album2 ( AlbumId, Title, ArtistId) values (2, 'Balls to the Wall', 2);
insert into album2 ( AlbumId, Title, ArtistId) values (3, 'Restless and Wild', 2);
insert into album2 ( AlbumId, Title, ArtistId) values (4, 'Let There Be Rock', 1);
insert into album2 ( AlbumId, Title, ArtistId) values (5, 'Big Ones', 3);
insert into album2 ( AlbumId, Title, ArtistId) values (6, 'Jagged Little Pill', 4);
insert into album2 ( AlbumId, Title, ArtistId) values (7, 'Facelift', 5);
insert into album2 ( AlbumId, Title, ArtistId) values (8, 'Warner 25 Anos', 6);
insert into album2 ( AlbumId, Title, ArtistId) values (9, 'Plays Metallica By Four Cellos', 7);
insert into album2 ( AlbumId, Title, ArtistId) values (10, 'Audioslave', 8);
insert into album2 ( AlbumId, Title, ArtistId) values (11, 'Out Of Exile', 8);
insert into album2 ( AlbumId, Title, ArtistId) values (12, 'BackBeat Soundtrack', 9);
insert into album2 ( AlbumId, Title, ArtistId) values (13, 'The Best Of Billy Cobham', 10);
insert into album2 ( AlbumId, Title, ArtistId) values (14, 'Alcohol Fueled Brewtality Live! [Disc 1]', 11);
insert into album2 ( AlbumId, Title, ArtistId) values (15, 'Alcohol Fueled Brewtality Live! [Disc 2]', 11);
insert into album2 ( AlbumId, Title, ArtistId) values (16, 'Black Sabbath', 12);
insert into album2 ( AlbumId, Title, ArtistId) values (17, 'Black Sabbath Vol. 4 (Remaster)', 12);
insert into album2 ( AlbumId, Title, ArtistId) values (18, 'Body Count', 13);
insert into album2 ( AlbumId, Title, ArtistId) values (19, 'Chemical Wedding', 14);
insert into album2 ( AlbumId, Title, ArtistId) values (20, 'The Best Of Buddy Guy - The Millenium Collection', 15);
insert into album2 ( AlbumId, Title, ArtistId) values (21, 'Prenda Minha', 16);
insert into album2 ( AlbumId, Title, ArtistId) values (22, 'Sozinho Remix Ao Vivo', 16);
insert into album2 ( AlbumId, Title, ArtistId) values (23, 'Minha Historia', 17);
insert into album2 ( AlbumId, Title, ArtistId) values (24, 'Afrociberdelia', 18);
insert into album2 ( AlbumId, Title, ArtistId) values (25, 'Da Lama Ao Caos', 18);
insert into album2 ( AlbumId, Title, ArtistId) values (26, 'Acústico MTV [Live]', 19);
insert into album2 ( AlbumId, Title, ArtistId) values (27, 'Cidade Negra - Hits', 19);
insert into album2 ( AlbumId, Title, ArtistId) values (28, 'Na Pista', 20);
insert into album2 ( AlbumId, Title, ArtistId) values (29, 'Axé Bahia 2001', 21);
insert into album2 ( AlbumId, Title, ArtistId) values (30, 'BBC Sessions [Disc 1] [Live]', 22);
insert into album2 ( AlbumId, Title, ArtistId) values (31, 'Bongo Fury', 23);
insert into album2 ( AlbumId, Title, ArtistId) values (32, 'Carnaval 2001', 21);
insert into album2 ( AlbumId, Title, ArtistId) values (33, 'Chill: Brazil (Disc 1)', 24);
insert into album2 ( AlbumId, Title, ArtistId) values (34, 'Chill: Brazil (Disc 2)', 6);
insert into album2 ( AlbumId, Title, ArtistId) values (35, 'Garage Inc. (Disc 1)', 50);
insert into album2 ( AlbumId, Title, ArtistId) values (36, 'Greatest Hits II', 51);
insert into album2 ( AlbumId, Title, ArtistId) values (37, 'Greatest Kiss', 52);
insert into album2 ( AlbumId, Title, ArtistId) values (38, 'Heart of the Night', 53);
insert into album2 ( AlbumId, Title, ArtistId) values (39, 'International Superhits', 54);
insert into album2 ( AlbumId, Title, ArtistId) values (40, 'Into The Light', 55);
insert into album2 ( AlbumId, Title, ArtistId) values (41, 'Meus Momentos', 56);
insert into album2 ( AlbumId, Title, ArtistId) values (42, 'Minha História', 57);
insert into album2 ( AlbumId, Title, ArtistId) values (43, 'MK III The Final Concerts [Disc 1]', 58);
insert into album2 ( AlbumId, Title, ArtistId) values (44, 'Physical Graffiti [Disc 1]', 22);
insert into album2 ( AlbumId, Title, ArtistId) values (45, 'Sambas De Enredo 2001', 21);
insert into album2 ( AlbumId, Title, ArtistId) values (46, 'Supernatural', 59);
insert into album2 ( AlbumId, Title, ArtistId) values (47, 'The Best of Ed Motta', 37);
insert into album2 ( AlbumId, Title, ArtistId) values (48, 'The Essential Miles Davis [Disc 1]', 68);
insert into album2 ( AlbumId, Title, ArtistId) values (49, 'The Essential Miles Davis [Disc 2]', 68);
insert into album2 ( AlbumId, Title, ArtistId) values (50, 'The Final Concerts (Disc 2)', 58);
insert into album2 ( AlbumId, Title, ArtistId) values (51, 'Up An'' Atom', 69);
insert into album2 ( AlbumId, Title, ArtistId) values (52, 'Vinícius De Moraes - Sem Limite', 70);
insert into album2 ( AlbumId, Title, ArtistId) values (53, 'Vozes do MPB', 21);
insert into album2 ( AlbumId, Title, ArtistId) values (54, 'Chronicle, Vol. 1', 76);
insert into album2 ( AlbumId, Title, ArtistId) values (55, 'Chronicle, Vol. 2', 76);
insert into album2 ( AlbumId, Title, ArtistId) values (56, 'Cássia Eller - Coleção Sem Limite [Disc 2]', 77);
insert into album2 ( AlbumId, Title, ArtistId) values (57, 'Cássia Eller - Sem Limite [Disc 1]', 77);
insert into album2 ( AlbumId, Title, ArtistId) values (58, 'Come Taste The Band', 58);
insert into album2 ( AlbumId, Title, ArtistId) values (59, 'Deep Purple In Rock', 58);
insert into album2 ( AlbumId, Title, ArtistId) values (60, 'Fireball', 58);
insert into album2 ( AlbumId, Title, ArtistId) values (61, 'Knocking at Your Back Door: The Best Of Deep Purple in the 80''s', 58);
insert into album2 ( AlbumId, Title, ArtistId) values (62, 'Machine Head', 58);
insert into album2 ( AlbumId, Title, ArtistId) values (63, 'Purpendicular', 58);
insert into album2 ( AlbumId, Title, ArtistId) values (64, 'Slaves And Masters', 58);
insert into album2 ( AlbumId, Title, ArtistId) values (65, 'Stormbringer', 58);
insert into album2 ( AlbumId, Title, ArtistId) values (66, 'The Battle Rages On', 58);
insert into album2 ( AlbumId, Title, ArtistId) values (67, 'Vault: Def Leppard''s Greatest Hits', 78);
insert into album2 ( AlbumId, Title, ArtistId) values (68, 'Outbreak', 79);
insert into album2 ( AlbumId, Title, ArtistId) values (69, 'Djavan Ao Vivo - Vol. 02', 80);
insert into album2 ( AlbumId, Title, ArtistId) values (70, 'Djavan Ao Vivo - Vol. 1', 80);
insert into album2 ( AlbumId, Title, ArtistId) values (71, 'Elis Regina-Minha História', 41);
insert into album2 ( AlbumId, Title, ArtistId) values (72, 'The Cream Of Clapton', 81);
insert into album2 ( AlbumId, Title, ArtistId) values (73, 'Unplugged', 81);
insert into album2 ( AlbumId, Title, ArtistId) values (74, 'Album Of The Year', 82);
insert into album2 ( AlbumId, Title, ArtistId) values (75, 'Angel Dust', 82);
insert into album2 ( AlbumId, Title, ArtistId) values (76, 'King For A Day Fool For A Lifetime', 82);
insert into album2 ( AlbumId, Title, ArtistId) values (77, 'The Real Thing', 82);
insert into album2 ( AlbumId, Title, ArtistId) values (78, 'Deixa Entrar', 83);
insert into album2 ( AlbumId, Title, ArtistId) values (79, 'In Your Honor [Disc 1]', 84);
insert into album2 ( AlbumId, Title, ArtistId) values (80, 'In Your Honor [Disc 2]', 84);
insert into album2 ( AlbumId, Title, ArtistId) values (81, 'One By One', 84);
insert into album2 ( AlbumId, Title, ArtistId) values (82, 'The Colour And The Shape', 84);
insert into album2 ( AlbumId, Title, ArtistId) values (83, 'My Way: The Best Of Frank Sinatra [Disc 1]', 85);
insert into album2 ( AlbumId, Title, ArtistId) values (84, 'Roda De Funk', 86);
insert into album2 ( AlbumId, Title, ArtistId) values (85, 'As Canções de Eu Tu Eles', 27);
insert into album2 ( AlbumId, Title, ArtistId) values (86, 'Quanta Gente Veio Ver (Live)', 27);
insert into album2 ( AlbumId, Title, ArtistId) values (87, 'Quanta Gente Veio ver--Bônus De Carnaval', 27);
insert into album2 ( AlbumId, Title, ArtistId) values (88, 'Faceless', 87);
insert into album2 ( AlbumId, Title, ArtistId) values (89, 'American Idiot', 54);
insert into album2 ( AlbumId, Title, ArtistId) values (90, 'Appetite for Destruction', 88);
insert into album2 ( AlbumId, Title, ArtistId) values (91, 'Use Your Illusion I', 88);
insert into album2 ( AlbumId, Title, ArtistId) values (92, 'Use Your Illusion II', 88);
insert into album2 ( AlbumId, Title, ArtistId) values (93, 'Blue Moods', 89);
insert into album2 ( AlbumId, Title, ArtistId) values (94, 'A Matter of Life and Death', 90);
insert into album2 ( AlbumId, Title, ArtistId) values (95, 'A Real Dead One', 90);
insert into album2 ( AlbumId, Title, ArtistId) values (96, 'A Real Live One', 90);
insert into album2 ( AlbumId, Title, ArtistId) values (97, 'Brave New World', 90);
insert into album2 ( AlbumId, Title, ArtistId) values (98, 'Dance Of Death', 90);
insert into album2 ( AlbumId, Title, ArtistId) values (99, 'Fear Of The Dark', 90);
insert into album2 ( AlbumId, Title, ArtistId) values (100, 'Iron Maiden', 90);
insert into album2 ( AlbumId, Title, ArtistId) values (101, 'Killers', 90);
insert into album2 ( AlbumId, Title, ArtistId) values (102, 'Live After Death', 90);
insert into album2 ( AlbumId, Title, ArtistId) values (103, 'Live At Donington 1992 (Disc 1)', 90);
insert into album2 ( AlbumId, Title, ArtistId) values (104, 'Live At Donington 1992 (Disc 2)', 90);
insert into album2 ( AlbumId, Title, ArtistId) values (105, 'No Prayer For The Dying', 90);
insert into album2 ( AlbumId, Title, ArtistId) values (106, 'Piece Of Mind', 90);
insert into album2 ( AlbumId, Title, ArtistId) values (107, 'Powerslave', 90);
insert into album2 ( AlbumId, Title, ArtistId) values (108, 'Rock In Rio [CD1]', 90);
insert into album2 ( AlbumId, Title, ArtistId) values (109, 'Rock In Rio [CD2]', 90);
insert into album2 ( AlbumId, Title, ArtistId) values (110, 'Seventh Son of a Seventh Son', 90);
insert into album2 ( AlbumId, Title, ArtistId) values (111, 'Somewhere in Time', 90);
insert into album2 ( AlbumId, Title, ArtistId) values (112, 'The Number of The Beast', 90);
insert into album2 ( AlbumId, Title, ArtistId) values (113, 'The X Factor', 90);
insert into album2 ( AlbumId, Title, ArtistId) values (114, 'Virtual XI', 90);
insert into album2 ( AlbumId, Title, ArtistId) values (115, 'Sex Machine', 91);
insert into album2 ( AlbumId, Title, ArtistId) values (116, 'Emergency On Planet Earth', 92);
insert into album2 ( AlbumId, Title, ArtistId) values (117, 'Synkronized', 92);
insert into album2 ( AlbumId, Title, ArtistId) values (118, 'The Return Of The Space Cowboy', 92);
insert into album2 ( AlbumId, Title, ArtistId) values (119, 'Get Born', 93);
insert into album2 ( AlbumId, Title, ArtistId) values (120, 'Are You Experienced?', 94);
insert into album2 ( AlbumId, Title, ArtistId) values (121, 'Surfing with the Alien (Remastered)', 95);
insert into album2 ( AlbumId, Title, ArtistId) values (122, 'Jorge Ben Jor 25 Anos', 46);
insert into album2 ( AlbumId, Title, ArtistId) values (123, 'Jota Quest-1995', 96);
insert into album2 ( AlbumId, Title, ArtistId) values (124, 'Cafezinho', 97);
insert into album2 ( AlbumId, Title, ArtistId) values (125, 'Living After Midnight', 98);
insert into album2 ( AlbumId, Title, ArtistId) values (126, 'Unplugged [Live]', 52);
insert into album2 ( AlbumId, Title, ArtistId) values (127, 'BBC Sessions [Disc 2] [Live]', 22);
insert into album2 ( AlbumId, Title, ArtistId) values (128, 'Coda', 22);
insert into album2 ( AlbumId, Title, ArtistId) values (129, 'Houses Of The Holy', 22);
insert into album2 ( AlbumId, Title, ArtistId) values (130, 'In Through The Out Door', 22);
insert into album2 ( AlbumId, Title, ArtistId) values (131, 'IV', 22);
insert into album2 ( AlbumId, Title, ArtistId) values (132, 'Led Zeppelin I', 22);
insert into album2 ( AlbumId, Title, ArtistId) values (133, 'Led Zeppelin II', 22);
insert into album2 ( AlbumId, Title, ArtistId) values (134, 'Led Zeppelin III', 22);
insert into album2 ( AlbumId, Title, ArtistId) values (135, 'Physical Graffiti [Disc 2]', 22);
insert into album2 ( AlbumId, Title, ArtistId) values (136, 'Presence', 22);
insert into album2 ( AlbumId, Title, ArtistId) values (137, 'The Song Remains The Same (Disc 1)', 22);
insert into album2 ( AlbumId, Title, ArtistId) values (138, 'The Song Remains The Same (Disc 2)', 22);
insert into album2 ( AlbumId, Title, ArtistId) values (139, 'A TempestadeTempestade Ou O Livro Dos Dias', 99);
insert into album2 ( AlbumId, Title, ArtistId) values (140, 'Mais Do Mesmo', 99);
insert into album2 ( AlbumId, Title, ArtistId) values (141, 'Greatest Hits', 100);
insert into album2 ( AlbumId, Title, ArtistId) values (142, 'Lulu Santos - RCA 100 Anos De Música - Álbum 01', 101);
insert into album2 ( AlbumId, Title, ArtistId) values (143, 'Lulu Santos - RCA 100 Anos De Música - Álbum 02', 101);
insert into album2 ( AlbumId, Title, ArtistId) values (144, 'Misplaced Childhood', 102);
insert into album2 ( AlbumId, Title, ArtistId) values (145, 'Barulhinho Bom', 103);
insert into album2 ( AlbumId, Title, ArtistId) values (146, 'Seek And Shall Find: More Of The Best (1963-1981)', 104);
insert into album2 ( AlbumId, Title, ArtistId) values (147, 'The Best Of Men At Work', 105);
insert into album2 ( AlbumId, Title, ArtistId) values (148, 'Black Album', 50);
insert into album2 ( AlbumId, Title, ArtistId) values (149, 'Garage Inc. (Disc 2)', 50);
insert into album2 ( AlbumId, Title, ArtistId) values (150, 'Kill ''Em All', 50);
insert into album2 ( AlbumId, Title, ArtistId) values (151, 'Load', 50);
insert into album2 ( AlbumId, Title, ArtistId) values (152, 'Master Of Puppets', 50);
insert into album2 ( AlbumId, Title, ArtistId) values (153, 'ReLoad', 50);
insert into album2 ( AlbumId, Title, ArtistId) values (154, 'Ride The Lightning', 50);
insert into album2 ( AlbumId, Title, ArtistId) values (155, 'St. Anger', 50);
insert into album2 ( AlbumId, Title, ArtistId) values (156, '...And Justice For All', 50);
insert into album2 ( AlbumId, Title, ArtistId) values (157, 'Miles Ahead', 68);
insert into album2 ( AlbumId, Title, ArtistId) values (158, 'Milton Nascimento Ao Vivo', 42);
insert into album2 ( AlbumId, Title, ArtistId) values (159, 'Minas', 42);
insert into album2 ( AlbumId, Title, ArtistId) values (160, 'Ace Of Spades', 106);
insert into album2 ( AlbumId, Title, ArtistId) values (161, 'Demorou...', 108);
insert into album2 ( AlbumId, Title, ArtistId) values (162, 'Motley Crue Greatest Hits', 109);
insert into album2 ( AlbumId, Title, ArtistId) values (163, 'From The Muddy Banks Of The Wishkah [Live]', 110);
insert into album2 ( AlbumId, Title, ArtistId) values (164, 'Nevermind', 110);
insert into album2 ( AlbumId, Title, ArtistId) values (165, 'Compositores', 111);
insert into album2 ( AlbumId, Title, ArtistId) values (166, 'Olodum', 112);
insert into album2 ( AlbumId, Title, ArtistId) values (167, 'Acústico MTV', 113);
insert into album2 ( AlbumId, Title, ArtistId) values (168, 'Arquivo II', 113);
insert into album2 ( AlbumId, Title, ArtistId) values (169, 'Arquivo Os Paralamas Do Sucesso', 113);
insert into album2 ( AlbumId, Title, ArtistId) values (170, 'Bark at the Moon (Remastered)', 114);
insert into album2 ( AlbumId, Title, ArtistId) values (171, 'Blizzard of Ozz', 114);
insert into album2 ( AlbumId, Title, ArtistId) values (172, 'Diary of a Madman (Remastered)', 114);
insert into album2 ( AlbumId, Title, ArtistId) values (173, 'No More Tears (Remastered)', 114);
insert into album2 ( AlbumId, Title, ArtistId) values (174, 'Tribute', 114);
insert into album2 ( AlbumId, Title, ArtistId) values (175, 'Walking Into Clarksdale', 115);
insert into album2 ( AlbumId, Title, ArtistId) values (176, 'Original Soundtracks 1', 116);
insert into album2 ( AlbumId, Title, ArtistId) values (177, 'The Beast Live', 117);
insert into album2 ( AlbumId, Title, ArtistId) values (178, 'Live On Two Legs [Live]', 118);
insert into album2 ( AlbumId, Title, ArtistId) values (179, 'Pearl Jam', 118);
insert into album2 ( AlbumId, Title, ArtistId) values (180, 'Riot Act', 118);
insert into album2 ( AlbumId, Title, ArtistId) values (181, 'Ten', 118);
insert into album2 ( AlbumId, Title, ArtistId) values (182, 'Vs.', 118);
insert into album2 ( AlbumId, Title, ArtistId) values (183, 'Dark Side Of The Moon', 120);
insert into album2 ( AlbumId, Title, ArtistId) values (184, 'Os Cães Ladram Mas A Caravana Não Pára', 121);
insert into album2 ( AlbumId, Title, ArtistId) values (185, 'Battlestar Galactica Podcast', 122);
insert into album2 ( AlbumId, Title, ArtistId) values (186, 'Greatest Hits I', 51);
insert into album2 ( AlbumId, Title, ArtistId) values (187, 'News Of The World', 51);
insert into album2 ( AlbumId, Title, ArtistId) values (188, 'Out Of Time', 123);
insert into album2 ( AlbumId, Title, ArtistId) values (189, 'Green', 125);
insert into album2 ( AlbumId, Title, ArtistId) values (190, 'New Adventures In Hi-Fi', 125);
insert into album2 ( AlbumId, Title, ArtistId) values (191, 'The Best Of R.E.M.: The IRS Years', 125);
insert into album2 ( AlbumId, Title, ArtistId) values (192, 'Cesta Básica', 126);
insert into album2 ( AlbumId, Title, ArtistId) values (193, 'Raul Seixas', 127);
insert into album2 ( AlbumId, Title, ArtistId) values (194, 'Blood Sugar Sex Magik', 128);
insert into album2 ( AlbumId, Title, ArtistId) values (195, 'By The Way', 128);
insert into album2 ( AlbumId, Title, ArtistId) values (196, 'Californication', 128);
insert into album2 ( AlbumId, Title, ArtistId) values (197, 'Retrospective I (1974-1980)', 129);
insert into album2 ( AlbumId, Title, ArtistId) values (198, 'Santana - As Years Go By', 59);
insert into album2 ( AlbumId, Title, ArtistId) values (199, 'Santana Live', 59);
insert into album2 ( AlbumId, Title, ArtistId) values (200, 'Maquinarama', 131);
insert into album2 ( AlbumId, Title, ArtistId) values (201, 'O Samba Poconé', 131);
insert into album2 ( AlbumId, Title, ArtistId) values (202, 'Judas 0: B-Sides and Rarities', 132);
insert into album2 ( AlbumId, Title, ArtistId) values (203, 'Rotten Apples: Greatest Hits', 132);
insert into album2 ( AlbumId, Title, ArtistId) values (204, 'A-Sides', 133);
insert into album2 ( AlbumId, Title, ArtistId) values (205, 'Morning Dance', 53);
insert into album2 ( AlbumId, Title, ArtistId) values (206, 'In Step', 134);
insert into album2 ( AlbumId, Title, ArtistId) values (207, 'Core', 135);
insert into album2 ( AlbumId, Title, ArtistId) values (208, 'Mezmerize', 136);
insert into album2 ( AlbumId, Title, ArtistId) values (209, '[1997] Black Light Syndrome', 137);
insert into album2 ( AlbumId, Title, ArtistId) values (210, 'Live [Disc 1]', 138);
insert into album2 ( AlbumId, Title, ArtistId) values (211, 'Live [Disc 2]', 138);
insert into album2 ( AlbumId, Title, ArtistId) values (212, 'The Singles', 139);
insert into album2 ( AlbumId, Title, ArtistId) values (213, 'Beyond Good And Evil', 140);
insert into album2 ( AlbumId, Title, ArtistId) values (214, 'Pure Cult: The Best Of The Cult (For Rockers, Ravers, Lovers & Sinners) [UK]', 140);
insert into album2 ( AlbumId, Title, ArtistId) values (215, 'The Doors', 141);
insert into album2 ( AlbumId, Title, ArtistId) values (216, 'The Police Greatest Hits', 142);
insert into album2 ( AlbumId, Title, ArtistId) values (217, 'Hot Rocks, 1964-1971 (Disc 1)', 143);
insert into album2 ( AlbumId, Title, ArtistId) values (218, 'No Security', 143);
insert into album2 ( AlbumId, Title, ArtistId) values (219, 'Voodoo Lounge', 143);
insert into album2 ( AlbumId, Title, ArtistId) values (220, 'Tangents', 144);
insert into album2 ( AlbumId, Title, ArtistId) values (221, 'Transmission', 144);
insert into album2 ( AlbumId, Title, ArtistId) values (222, 'My Generation - The Very Best Of The Who', 145);
insert into album2 ( AlbumId, Title, ArtistId) values (223, 'Serie Sem Limite (Disc 1)', 146);
insert into album2 ( AlbumId, Title, ArtistId) values (224, 'Serie Sem Limite (Disc 2)', 146);
insert into album2 ( AlbumId, Title, ArtistId) values (225, 'Acústico', 147);
insert into album2 ( AlbumId, Title, ArtistId) values (226, 'Volume Dois', 147);
insert into album2 ( AlbumId, Title, ArtistId) values (227, 'Battlestar Galactica: The Story So Far', 148);
insert into album2 ( AlbumId, Title, ArtistId) values (228, 'Battlestar Galactica, Season 3', 148);
insert into album2 ( AlbumId, Title, ArtistId) values (229, 'Heroes, Season 1', 149);
insert into album2 ( AlbumId, Title, ArtistId) values (230, 'Lost, Season 3', 150);
insert into album2 ( AlbumId, Title, ArtistId) values (231, 'Lost, Season 1', 150);
insert into album2 ( AlbumId, Title, ArtistId) values (232, 'Lost, Season 2', 150);
insert into album2 ( AlbumId, Title, ArtistId) values (233, 'Achtung Baby', 151);
insert into album2 ( AlbumId, Title, ArtistId) values (234, 'All That You Can''t Leave Behind', 151);
insert into album2 ( AlbumId, Title, ArtistId) values (235, 'B-Sides 1980-1990', 151);
insert into album2 ( AlbumId, Title, ArtistId) values (236, 'How To Dismantle An Atomic Bomb', 151);
insert into album2 ( AlbumId, Title, ArtistId) values (237, 'Pop', 151);
insert into album2 ( AlbumId, Title, ArtistId) values (238, 'Rattle And Hum', 151);
insert into album2 ( AlbumId, Title, ArtistId) values (239, 'The Best Of 1980-1990', 151);
insert into album2 ( AlbumId, Title, ArtistId) values (240, 'War', 151);
insert into album2 ( AlbumId, Title, ArtistId) values (241, 'Zooropa', 151);
insert into album2 ( AlbumId, Title, ArtistId) values (242, 'UB40 The Best Of - Volume Two [UK]', 152);
insert into album2 ( AlbumId, Title, ArtistId) values (243, 'Diver Down', 153);
insert into album2 ( AlbumId, Title, ArtistId) values (244, 'The Best Of Van Halen, Vol. I', 153);
insert into album2 ( AlbumId, Title, ArtistId) values (245, 'Van Halen', 153);
insert into album2 ( AlbumId, Title, ArtistId) values (246, 'Van Halen III', 153);
insert into album2 ( AlbumId, Title, ArtistId) values (247, 'Contraband', 154);
insert into album2 ( AlbumId, Title, ArtistId) values (248, 'Vinicius De Moraes', 72);
insert into album2 ( AlbumId, Title, ArtistId) values (249, 'Ao Vivo [IMPORT]', 156);
insert into album2 ( AlbumId, Title, ArtistId) values (250, 'The Office, Season 1', 157);
insert into album2 ( AlbumId, Title, ArtistId) values (251, 'The Office, Season 2', 157);
insert into album2 ( AlbumId, Title, ArtistId) values (252, 'The Office, Season 3', 157);
insert into album2 ( AlbumId, Title, ArtistId) values (253, 'Un-Led-Ed', 158);
insert into album2 ( AlbumId, Title, ArtistId) values (254, 'Battlestar Galactica (Classic), Season 1', 159);
insert into album2 ( AlbumId, Title, ArtistId) values (255, 'Aquaman', 160);
insert into album2 ( AlbumId, Title, ArtistId) values (256, 'Instant Karma: The Amnesty International Campaign to Save Darfur', 151);
insert into album2 ( AlbumId, Title, ArtistId) values (257, 'Speak of the Devil', 114);
insert into album2 ( AlbumId, Title, ArtistId) values (258, '20th Century Masters - The Millennium Collection: The Best of Scorpions', 180);
insert into album2 ( AlbumId, Title, ArtistId) values (259, 'House of Pain', 181);
insert into album2 ( AlbumId, Title, ArtistId) values (260, 'Radio Brasil (O Som da Jovem Vanguarda) - Seleccao de Henrique Amaro', 36);
insert into album2 ( AlbumId, Title, ArtistId) values (261, 'Macworld 2008 Keynote Address', 197);
insert into album2 ( AlbumId, Title, ArtistId) values (262, 'Cake: B-Sides and Rarities', 198);
insert into album2 ( AlbumId, Title, ArtistId) values (263, 'LOST, Season 4', 150);
insert into album2 ( AlbumId, Title, ArtistId) values (264, 'Hanselminutes', 199);
insert into album2 ( AlbumId, Title, ArtistId) values (265, 'stackoverflow', 200);
insert into album2 ( AlbumId, Title, ArtistId) values (266, '1999 Grammy Nominees: Rap', 201);
insert into album2 ( AlbumId, Title, ArtistId) values (267, 'Ill Communication', 202);
insert into album2 ( AlbumId, Title, ArtistId) values (268, 'Billy Cobham Presents North by Northwest', 10);
insert into album2 ( AlbumId, Title, ArtistId) values (269, 'Black Elk Speaks', 203);
insert into album2 ( AlbumId, Title, ArtistId) values (270, 'Star Trek: First Contact', 204);
insert into album2 ( AlbumId, Title, ArtistId) values (271, 'Quiet Songs', 205);
insert into album2 ( AlbumId, Title, ArtistId) values (272, 'Muso Ko', 206);
insert into album2 ( AlbumId, Title, ArtistId) values (273, 'Realize', 207);
insert into album2 ( AlbumId, Title, ArtistId) values (274, 'Every Kind of Light', 208);
insert into album2 ( AlbumId, Title, ArtistId) values (275, 'Duos II', 209);
insert into album2 ( AlbumId, Title, ArtistId) values (276, 'Worlds', 210);
insert into album2 ( AlbumId, Title, ArtistId) values (277, 'The Best of Beethoven', 211);
insert into album2 ( AlbumId, Title, ArtistId) values (278, 'Temple of the Dog', 212);
insert into album2 ( AlbumId, Title, ArtistId) values (279, 'Carry On', 213);
insert into album2 ( AlbumId, Title, ArtistId) values (280, 'Revelations', 8);
insert into album2 ( AlbumId, Title, ArtistId) values (281, '.NET Rocks!', 214);
insert into album2 ( AlbumId, Title, ArtistId) values (282, 'Monica''s podcast', 215);
insert into album2 ( AlbumId, Title, ArtistId) values (283, 'Alt.NET Podcast', 216);
insert into album2 ( AlbumId, Title, ArtistId) values (284, 'Adorate Deum: Gregorian Chant from the Proper of the Mass', 217);
insert into album2 ( AlbumId, Title, ArtistId) values (285, 'Allegri: Miserere', 218);
insert into album2 ( AlbumId, Title, ArtistId) values (286, 'Pachelbel: Canon & Gigue', 219);
insert into album2 ( AlbumId, Title, ArtistId) values (287, 'Vivaldi: The Four Seasons', 220);
insert into album2 ( AlbumId, Title, ArtistId) values (288, 'Bach: Violin Concertos', 221);
insert into album2 ( AlbumId, Title, ArtistId) values (289, 'Bach: Goldberg Variations', 222);
insert into album2 ( AlbumId, Title, ArtistId) values (290, 'Bach: The Cello Suites', 223);
insert into album2 ( AlbumId, Title, ArtistId) values (291, 'Handel: The Messiah (Highlights)', 224);
insert into album2 ( AlbumId, Title, ArtistId) values (292, 'The World of Classical Favourites', 225);
insert into album2 ( AlbumId, Title, ArtistId) values (293, 'Sir Neville Marriner: A Celebration', 226);
insert into album2 ( AlbumId, Title, ArtistId) values (294, 'Mozart: Wind Concertos', 227);
insert into album2 ( AlbumId, Title, ArtistId) values (295, 'Haydn: Symphonies 99 - 104', 228);
insert into album2 ( AlbumId, Title, ArtistId) values (296, 'Beethoven: Symhonies Nos. 5 & 6', 229);
insert into album2 ( AlbumId, Title, ArtistId) values (297, 'A Soprano Inspired', 230);
insert into album2 ( AlbumId, Title, ArtistId) values (298, 'Great Opera Choruses', 231);
insert into album2 ( AlbumId, Title, ArtistId) values (299, 'Wagner: Favourite Overtures', 232);
insert into album2 ( AlbumId, Title, ArtistId) values (300, 'Fauré: Requiem, Ravel: Pavane & Others', 233);
insert into album2 ( AlbumId, Title, ArtistId) values (301, 'Tchaikovsky: The Nutcracker', 234);
insert into album2 ( AlbumId, Title, ArtistId) values (302, 'The Last Night of the Proms', 235);
insert into album2 ( AlbumId, Title, ArtistId) values (303, 'Puccini: Madama Butterfly - Highlights', 236);
insert into album2 ( AlbumId, Title, ArtistId) values (304, 'Holst: The Planets, Op. 32 & Vaughan Williams: Fantasies', 237);
insert into album2 ( AlbumId, Title, ArtistId) values (305, 'Pavarotti''s Opera Made Easy', 238);
insert into album2 ( AlbumId, Title, ArtistId) values (306, 'Great Performances - Barber''s Adagio and Other Romantic Favorites for Strings', 239);
insert into album2 ( AlbumId, Title, ArtistId) values (307, 'Carmina Burana', 240);
insert into album2 ( AlbumId, Title, ArtistId) values (308, 'A Copland Celebration, Vol. I', 241);

